-- Création simplifiée de la table tblCompte (uniquement emp_id + firstname)
-- Exécuter ce script dans votre base de données (par ex. via phpMyAdmin ou mysql CLI)
CREATE TABLE IF NOT EXISTS `tblCompte` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` INT NOT NULL,
  `firstname` VARCHAR(255) DEFAULT NULL,
  `services` TEXT DEFAULT NULL,
  `type_compte` VARCHAR(255) DEFAULT NULL,
  `devise_pref` VARCHAR(20) DEFAULT NULL,
  `objectif` TEXT DEFAULT NULL,
  `access` TEXT DEFAULT NULL,
  `titre` VARCHAR(20) DEFAULT NULL,
  `noms` VARCHAR(255) DEFAULT NULL,
  `prenom2` VARCHAR(255) DEFAULT NULL,
  `nationalite` VARCHAR(100) DEFAULT NULL,
  `lieu_naiss` VARCHAR(255) DEFAULT NULL,
  `pays` VARCHAR(100) DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `genre` VARCHAR(10) DEFAULT NULL,
  `situation` VARCHAR(100) DEFAULT NULL,
  `id_type` VARCHAR(255) DEFAULT NULL,
  `id_num` VARCHAR(255) DEFAULT NULL,
  `date_deliv` DATE DEFAULT NULL,
  `date_exp` DATE DEFAULT NULL,
  `fiscal_pays` VARCHAR(100) DEFAULT NULL,
  `nip` VARCHAR(100) DEFAULT NULL,
  `mobile1` VARCHAR(50) DEFAULT NULL,
  `mobile2` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `adr_rue` VARCHAR(255) DEFAULT NULL,
  `ville` VARCHAR(100) DEFAULT NULL,
  `adr_pays` VARCHAR(100) DEFAULT NULL,
  `employeur` VARCHAR(255) DEFAULT NULL,
  `cond` TEXT DEFAULT NULL,
  `revenu` VARCHAR(50) DEFAULT NULL,
  `etabliss` VARCHAR(255) DEFAULT NULL,
  `ident_etud` VARCHAR(255) DEFAULT NULL,
  `date_enregistrement` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`emp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
